/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.nelkinda.training.hello.kotlin-application-conventions")
    id("org.springframework.boot") version "3.1.0"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("com.nelkinda.training.hello.app.AppKt")
}
